### ISSUE TITLE
GitHub OAuth Login Failure - Too many Redirs

### ISSUE THREAD

**Issue by NDuma** [bitwrap/bitwrap-io-npm#3]
![OAuth - Fail & Redirs](http://image.prntscr.com/image/e9e54c4328b844c09e22841ce91f52ca.png)
via ads paid here http://prntscr.com/batkz4

**Comment by stackdump** [comment]
thanks for reporting this @NDuma  - currently this feature assumes that if you've logged into github that you should be allowed access to the demo ( this is not the case )

I'll be addressing this problem by automatically granting the correct github permissions for any user to login

**Comment by stackdump** [comment]
Shifting work to the python version of the appserver, will re-implement authentication as described in this ticket as part of that project.

see updated project here: https://github.com/bitwrap/bitwrap-io
